### ISSUE TITLE
W4: read parameters

### ISSUE THREAD

**Issue by nasay** [nathanwbrei/cfdlab#29]
Modify  the  readParameters  function  to  be  able  to  read  all  three  variables  iProc,  jProc  and
kProc, describing the number of processes per axis.

**Comment by irvcaza** [comment]
Here I want to open the discussion. Here, if we read these parameters from the file then if you want to run the program with different amount of processes then you have to change the file of parameters and the parameters when you run the function, since both have to match
We also can calculate iProc, jProc and kProc with information of the total number of processes, and the geometry of the cavity. It can get a little nasty but I think it will work.
What do you say? How rebel do you feel?

**Comment by nasay** [comment]
I would say, that it is not so important, but from the description it looks like this parameters are describing number of processes, and not vice versa.
